apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s5qiyn52p-nodejs-gitops
  description: This is GitOps manifest for s5qiyn52p-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=s5qiyn52p-nodejs
    backstage.io/kubernetes-id: s5qiyn52p-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s5qiyn52p-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s5qiyn52p-nodejs
